'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.586
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_2212_Phelan_Final.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ali1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ali1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ali2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ali2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ali3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ali3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlistarSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AlistarSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property brand1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brand1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property brand2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brand2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property brand3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brand3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BrandSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("BrandSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property cho1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cho1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cho2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cho2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cho3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cho3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChoSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ChoSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property jarvan1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jarvan1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jarvan2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jarvan2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jarvan3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jarvan3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JarvinSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("JarvinSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kayle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kayle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kayle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kayle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kayle3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kayle3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KayleSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("KayleSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kog1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kog1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kog2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kog2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kog3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kog3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KogSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("KogSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property League_of_Legends() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("League-of-Legends", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leblanc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leblanc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leblanc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leblanc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leblanc3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leblanc3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LeBlancSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("LeBlancSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property leona1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leona1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leona2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leona2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leona3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leona3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LeonaSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("LeonaSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property lux1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lux1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lux2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lux2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lux3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lux3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LuxSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("LuxSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property morde1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("morde1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property morde2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("morde2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property morde3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("morde3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MordeSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MordeSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property morgana1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("morgana1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property morgana2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("morgana2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property morgana3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("morgana3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MorgSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MorgSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property mumu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mumu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mumu2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mumu2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mumu3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mumu3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MumuSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MumuSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property NunuSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NunuSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property poppy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poppy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property poppy2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poppy2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property poppy3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poppy3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PoppySelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("PoppySelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property purple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("purple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seguani1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seguani1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seguani2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seguani2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seguani3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seguani3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SeguaniSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SeguaniSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sona1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sona1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sona2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sona2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sona3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sona3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SonaSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SonaSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property twitch1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twitch1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property twitch2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twitch2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property twitch3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twitch3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property urgot1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("urgot1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property urgot2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("urgot2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property urgot3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("urgot3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property viegar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viegar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property viegar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viegar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property viegar3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viegar3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ViegarSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ViegarSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property wukong1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wukong1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wukong2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wukong2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wukong3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wukong3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WuSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WuSelect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ww1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ww1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ww2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ww2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ww3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ww3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xin2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xin2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xin3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xin3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property XinSelect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("XinSelect", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
